export default defineEventHandler(() => [{
        date: "Aut, 2019",
        title: "ذكري",
        description: "Dikri is a mobile application that enables the user to read the daily supplications of a Muslim, designed to facilitate the reading process and simplify the idea.",
        link: "https://play.google.com/store/apps/details?id=net.casetrue.dikri",
        tools: ['XML', 'JAVA', 'Android Studio'],
        cover: "/img/dikri-cover.webp",
    },
    {
        date: "Mars, 2020",
        title: "doing",
        description: "Doing, is a mobile application that enables the user to create, delete and modify daily tasks in an easy and simple way, with three languages (Arabic, French, and English) and light and dark mode. ",
        link: "https://play.google.com/store/apps/details?id=net.casetrue.doing",
        tools: ['XML', 'JAVA', 'Android Studio', 'Sqlite'],
        cover: "/img/doing-cover.webp",
    },
    {
        date: "Mars, 2021",
        title: "casetrue",
        description: "casetrue is a website that let you store photos by url and search for a beatifull images",
        link: "http://www.casetrue.com",
        tools: ['vuejs', 'vuex', 'laravel', 'PostgreSql'],
        cover: "/img/casetrue-cover.svg",
    },
]);